name: Test Ruby Installation

on: # run this workflow when a push has been made to `Jekyll-Alf` branch
  push:
    branches:
      - Jekyll-Alf


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
        - run: ruby hello.rb
          name: Install Ruby dependencies
          - run:        #This installs Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle