jobs:
    build:
    runs-on: ubuntu-16.04  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - run: ruby hello.rb
    - run: ruby hello.rb